application: machiasobi-tools
version: 2
runtime: go
api_version: go1

automatic_scaling:
  min_idle_instances: automatic
  max_idle_instances: 1
  min_pending_latency: 3000ms
  max_pending_latency: automatic
  max_concurrent_requests: 50

handlers:
- url: /api/.*
  script: _go_app
  secure: always
- url: /
  static_files: static/index.html
  upload: /
  secure: always
- url: /
  static_dir: static
  secure: always

skip_files:
# default parameter
- ^(.*/)?#.*#
- ^(.*/)?.*~
- ^(.*/)?.*\.py[co]
- ^(.*/)?.*/RCS/.*
- ^(.*/)?\..*

# original parameter
- ^(.*/)?assets/.*
- ^(.*/)?build/.*
- ^(.*/)?test/.*
- ^(.*/)?templates/.*
- ^(.*/)?node_modules/.*
